#!/usr/bin/env node
// scripts/agent/gen-content.cjs  (npm run agent:content)
//
// The agent reads two documents at run time: the voice and claims guide and the Hub Guide's
// help articles. A serverless build does not ship docs/, so this writes them into
// src/lib/agent/generated/ as TypeScript string constants. Run it after editing either.
// `node scripts/agent/gen-content.cjs --check` exits 1 when the generated files are stale;
// scripts/verify.cjs runs that check, so a guide edit cannot ship without its generated copy.
const fs = require('fs'), path = require('path')

const ROOT = path.resolve(__dirname, '..', '..')
const OUT = path.join(ROOT, 'src', 'lib', 'agent', 'generated')
const header = '// GENERATED by scripts/agent/gen-content.cjs. Do not edit; edit the source document and rerun.\n'

function voiceGuide() {
  const text = fs.readFileSync(path.join(ROOT, 'docs', 'marketing', 'voice-and-claims-guide.md'), 'utf8').replace(/\r\n/g, '\n')
  return `${header}// Source: docs/marketing/voice-and-claims-guide.md\nexport const VOICE_GUIDE = ${JSON.stringify(text)}\n`
}

function helpCorpus() {
  const dir = path.join(ROOT, 'docs', 'help')
  const files = fs.existsSync(dir) ? fs.readdirSync(dir).filter((f) => f.endsWith('.md') && f !== 'README.md' && f !== 'EXEMPT.md').sort() : []
  const articles = files.map((f) => ({ file: `docs/help/${f}`, text: fs.readFileSync(path.join(dir, f), 'utf8').replace(/\r\n/g, '\n') }))
  const exemptFile = path.join(dir, 'EXEMPT.md')
  const exempt = fs.existsSync(exemptFile) ? fs.readFileSync(exemptFile, 'utf8').replace(/\r\n/g, '\n') : ''
  return `${header}// Source: docs/help/*.md\nexport const HELP_SOURCES: Array<{ file: string; text: string }> = ${JSON.stringify(articles, null, 1)}\nexport const HELP_EXEMPT = ${JSON.stringify(exempt)}\n`
}

const targets = { 'voice-guide.ts': voiceGuide(), 'help-corpus.ts': helpCorpus() }
const check = process.argv.includes('--check')
let stale = 0
fs.mkdirSync(OUT, { recursive: true })
for (const [name, body] of Object.entries(targets)) {
  const p = path.join(OUT, name)
  const cur = fs.existsSync(p) ? fs.readFileSync(p, 'utf8').replace(/\r\n/g, '\n') : null
  if (cur === body) continue
  if (check) { console.error(`stale: src/lib/agent/generated/${name} (run node scripts/agent/gen-content.cjs)`); stale++ }
  else { fs.writeFileSync(p, body); console.log(`wrote src/lib/agent/generated/${name}`) }
}
if (check) { console.log(stale ? `FAIL: ${stale} stale` : 'generated content is current'); process.exit(stale ? 1 : 0) }
